apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      port: 4318
      targetPort: 4318
  type: LoadBalancer
